[req]
distinguished_name = req_distinguished_name
req_extensions = v3_req
prompt = no

[req_distinguished_name]
CN = beta

[ v3_req ]
basicConstraints = CA:FALSE
keyUsage = digitalSignature
subjectAltName = @alt_names

[alt_names]
DNS.1  = 54494dfffe450056
DNS.2  = 2ccf67fffe5b0274 
